//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaladarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cabecera
    {
        public Nullable<System.Guid> iDCliente { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> Lineas { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<System.Guid> iDVenta { get; set; }
        public int Row { get; set; }
        public string Status { get; set; }
    }
}
