//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaladarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuentos
    {
        public string Descuento { get; set; }
        public Nullable<int> Porcentaje { get; set; }
        public int Row { get; set; }
    }
}
