//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaladarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public string Producto1 { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.Guid> iDProducto { get; set; }
        public int Row { get; set; }
        public byte[] Foto { get; set; }
    }
}
